{
  try {
    resource.cancel();
  }
 catch (  IOException e) {
    logger.debug("",e);
  }
}
